# Trabalho 2 -Analise Modal Estrutra


Considere o pórtico representado na figura, adimitamos apenas a massa dos pisos(**M1** a **M3**) e a rigidez de pilares ao nível de cada piso (**K2** a **K3**)



<img src="portico.jpg" alt="portico" width="200"/>

1. Escreva as equações diferenciais de equilíbrio em coordenadas modais e represente graficamente os respetivos modos de vibrações. (ex. $M_{1} = 35t$;  $M_{2} = 30t$; $M_{3} = 20t$; $K_{1} = 18 \times 10^{3} kN/m $; $K_{2} = 20 \times 10^{3} kN/m$  e $K_{3} = 22 \times 10^{3} kN/m$
2. Escreva e implemente um algoritmo numérico que permita determinar entre $t_0$ e $t_f$ os deslocamentos e acelerações de cada piso ($y_i(t)$ e $ \ddot{y}_{i}(t)$). Considere como condições iniciais:
$$y_{1}(t_{0}) = \bar{y}_{1}$$
$$y_{2}(t_{0}) = \bar{y}_{2}$$
$$y_{3}(t_{0}) = \bar{y}_{3}$$
$$\dot{y}_{1}(t_{0}) = 0$$
$$\dot{y}_{2}(t_{0}) = 0$$
$$\dot{y}_{3}(t_{0}) = 0$$

1. a) As equações em coordenadas modais são:

1. b) Os modos de vibrações são:
<img src="modos.jpg" alt="modos" width="500"/>

In [1]:
import matplotlib.pyplot as plt
import numpy as np
from scipy.linalg import eigh


%matplotlib inline
# Definição dos parâmetros:
m1 = 35000 # massa do 1º piso em Kg
m2 = 30000 # massa do 2º piso em Kg
m3 = 20000 # massa do 2º piso em Kg
k1 = 2*18000 # Rigidez do pilar ao nível do 1º piso em kN/m2
k2 = 2*20000 # Rigidez do pilar ao nível do 2º piso em kN/m2
k3 = 2*22000 # Rigidez do pilar ao nível do 3º piso em kN/m2
y = np.array([0.02, 0.01, 0.03]) # condições iniciais
y_deriv = np.array([0.01, 0.02, 0.03]) # condições inicias



m = [m1, m2, m3]
m = np.diag(m)
k = np.array([[k1+k2,-k2,0], [-k2,k2+k3,-k3], [0,-k3,k3]], dtype=np.float)
eigvals, eigvecs = eigh(k, m, eigvals_only=False)
print(m)
print(k)
print(eigvecs)
print(eigvals)



[[35000     0     0]
 [    0 30000     0]
 [    0     0 20000]]
[[ 76000. -40000.      0.]
 [-40000.  84000. -44000.]
 [     0. -44000.  44000.]]
[[-2.30748612e-03  4.39992917e-03  1.97168956e-03]
 [-3.78935860e-03 -3.53735136e-05 -4.35578276e-03]
 [-4.37530351e-03 -4.01487408e-03  3.83894586e-03]]
[0.29462614 2.18061664 4.69618578]


In [ ]:
y

In [13]:
# definir os parametros em coord. modais
m_generalizada = np.matmul(eigvecs.T,m)
m_generalizada = np.matmul(m_generalizada,eigvecs)
k_generalizada = np.matmul(eigvecs.T,k)
k_generalizada = np.matmul(k_generalizada,eigvecs)
factor_conv = (np.matmul(eigvecs.T,m))/m_generalizada
y_coord_modal = np.matmul(factor_conv,y.T)
print(y_coord_modal)

[-2.63191373e+15 -2.93433160e+16  1.50778188e+15]
