# Trabalho 2 -Analise Modal Estrutra


Considere o pórtico representado na figura, adimitamos apenas a massa dos pisos(**M1** a **M3**) e a rigidez de pilares ao nível de cada piso (**K2** a **K3**)



<img src="portico.jpg" alt="portico" width="200"/>

1. Escreva as equações diferenciais de equilíbrio em coordenadas modais e represente graficamente os respetivos modos de vibrações. (ex. $M_{1} = 35t$;  $M_{2} = 30t$; $M_{3} = 20t$; $K_{1} = 18 \times 10^{3} kN/m $; $K_{2} = 20 \times 10^{3} kN/m$  e $K_{3} = 22 \times 10^{3} kN/m$
2. Escreva e implemente um algoritmo numérico que permita determinar entre $t_0$ e $t_f$ os deslocamentos e acelerações de cada piso ($y_i(t)$ e $ \ddot{y}_{i}(t)$). Considere como condições iniciais:
$$y_{1}(t_{0}) = \bar{y}_{1}$$
$$y_{2}(t_{0}) = \bar{y}_{2}$$
$$y_{3}(t_{0}) = \bar{y}_{3}$$
$$\dot{y}_{1}(t_{0}) = 0$$
$$\dot{y}_{2}(t_{0}) = 0$$
$$\dot{y}_{3}(t_{0}) = 0$$

1. a) As equações em coordenadas modais são:

1. b) Os modos de vibrações são:
<img src="modos.jpg" alt="modos" width="500"/>

In [45]:
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
# Definição dos parâmetros:
m1 = 64000 # massa do 1º piso em Kg
m2 = 64000 # massa do 2º piso em Kg
m3 = 48000 # massa do 2º piso em Kg
k1 = 22221 # Rigidez do pilar ao nível do 1º piso em kN/m2
k2 = 19382 # Rigidez do pilar ao nível do 2º piso em kN/m2
k3 = 9804 # Rigidez do pilar ao nível do 3º piso em kN/m2

m = [m1, m2, m3]
m = np.diag(m)
k = np.array([[k1+k2,-k2,0], [0,k2+k3,-k3], [0,0,k3]], dtype=np.float)
k

array([[ 41603., -19382.,      0.],
       [     0.,  29186.,  -9804.],
       [     0.,      0.,   9804.]])

In [44]:
m[2,2]

48000

In [11]:
d = np.diag(x)

d

array([0, 4, 8])

In [12]:
novad=np.diag(d)
novad

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])